[seraphim]
user = "kivikakk"
server = false

[piret]
user = "kivikakk"
server = false

[piretike]
user = "kivikakk"
server = false

[kala]
user = "charlotte"
server = true
hostId = "6fcf22f5"
[kala.net]
dev = "ens3"
ipv4 = "51.161.134.17/32"
gwv4 = "51.161.134.1/32"
ipv6 = "2402:1f00:8100:400::17b4/64"
gwv6 = "2402:1f00:8100:400::1#ens3"
