[seraphim]
user = "kivikakk"
server = false

[orav]
user = "kivikakk"
server = true
hostId = "a1b2c3d4"
[orav.net]
dev = "eth0"
ipv4 = "95.217.1.49/32"
gwv4 = "172.31.1.1/32"
ipv6 = "2a01:4f9:c012:6a55::1/64"
gwv6 = "fe80::1#eth0"